-- =============================================================================
-- IBM DB2 DDL Migration Script for Simple Report Centre
-- Target Database: IBM DB2 LUW / Enterprise Server
-- =============================================================================

-- 1. Table: USERS (Admin Portal Users)
CREATE TABLE USERS (
    ID VARCHAR(36) NOT NULL,
    USERNAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('SUPER_ADMIN', 'OPERATOR', 'AUDITOR')),
    CONSTRAINT CK_USERS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- 2. Table: THIRD_PARTY_CLIENTS (API Integration Keys)
CREATE TABLE THIRD_PARTY_CLIENTS (
    ID VARCHAR(36) NOT NULL,
    CLIENT_NAME VARCHAR(128) NOT NULL,
    API_KEY VARCHAR(64) NOT NULL,
    API_SECRET_HASH VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    ALLOWED_IPS VARCHAR(2048) DEFAULT '',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_TP_CLIENTS PRIMARY KEY (ID),
    CONSTRAINT UK_TP_CLIENTS_KEY UNIQUE (API_KEY),
    CONSTRAINT CK_TP_CLIENTS_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'REVOKED'))
);

CREATE INDEX IDX_CLIENTS_API_KEY ON THIRD_PARTY_CLIENTS (API_KEY);

-- 3. Table: REPORTS (Document Lifecycle and Storage References)
CREATE TABLE REPORTS (
    ID VARCHAR(36) NOT NULL,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    FILE_SIZE_BYTES BIGINT NOT NULL,
    PAGE_COUNT INTEGER,
    RAW_STORAGE_PATH VARCHAR(512) NOT NULL,
    WATERMARKED_STORAGE_PATH VARCHAR(512),
    CHECKSUM_SHA256 VARCHAR(64),
    STATUS VARCHAR(30) DEFAULT 'PENDING_WATERMARK' NOT NULL,
    UPLOADED_BY_TYPE VARCHAR(20) NOT NULL,
    UPLOADED_BY_ID VARCHAR(36) NOT NULL,
    BENCHMARK_TAG VARCHAR(100),
    METADATA CLOB(64K),
    ERROR_REASON VARCHAR(1024),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_REPORTS PRIMARY KEY (ID),
    CONSTRAINT CK_REPORTS_STATUS CHECK (STATUS IN ('PENDING_WATERMARK', 'PROCESSING', 'READY', 'FAILED')),
    CONSTRAINT CK_REPORTS_UPLOADER CHECK (UPLOADED_BY_TYPE IN ('ADMIN_USER', 'THIRD_PARTY'))
);

CREATE INDEX IDX_REPORTS_STATUS ON REPORTS (STATUS);
CREATE INDEX IDX_REPORTS_BENCHMARK ON REPORTS (BENCHMARK_TAG);
CREATE INDEX IDX_REPORTS_CREATED ON REPORTS (CREATED_AT DESC);
CREATE INDEX IDX_REPORTS_UPLOADER ON REPORTS (UPLOADED_BY_ID, UPLOADED_BY_TYPE);

-- 4. Table: AUDIT_LOGS (Immutable System Activity Trail)
CREATE TABLE AUDIT_LOGS (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ACTOR_TYPE VARCHAR(20) NOT NULL,
    ACTOR_ID VARCHAR(36) NOT NULL,
    ACTION VARCHAR(30) NOT NULL,
    TARGET_REPORT_ID VARCHAR(36),
    IP_ADDRESS VARCHAR(45) NOT NULL,
    USER_AGENT VARCHAR(512),
    REQUEST_DETAILS CLOB(64K),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_REPORT FOREIGN KEY (TARGET_REPORT_ID)
        REFERENCES REPORTS (ID) ON DELETE SET NULL,
    CONSTRAINT CK_AUDIT_ACTOR CHECK (ACTOR_TYPE IN ('ADMIN_USER', 'THIRD_PARTY')),
    CONSTRAINT CK_AUDIT_ACTION CHECK (ACTION IN ('UPLOAD', 'DOWNLOAD', 'DELETE', 'LOGIN', 'KEY_ROTATION'))
);

CREATE INDEX IDX_AUDIT_ACTOR ON AUDIT_LOGS (ACTOR_ID, ACTOR_TYPE);
CREATE INDEX IDX_AUDIT_ACTION ON AUDIT_LOGS (ACTION);
CREATE INDEX IDX_AUDIT_CREATED ON AUDIT_LOGS (CREATED_AT DESC);
