-- =============================================================================
-- V2: Add SYSTEM_ERROR_LOGS table for exception tracking
-- =============================================================================

CREATE TABLE SYSTEM_ERROR_LOGS (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ERROR_MESSAGE VARCHAR(2000) NOT NULL,
    EXCEPTION_CLASS VARCHAR(500) NOT NULL,
    STACK_TRACE CLOB(64K),
    HTTP_METHOD VARCHAR(10),
    REQUEST_URI VARCHAR(1000),
    HTTP_STATUS INTEGER,
    USER_AGENT VARCHAR(512),
    IP_ADDRESS VARCHAR(45),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_SYSTEM_ERROR_LOGS PRIMARY KEY (ID)
);

CREATE INDEX IDX_ERRLOG_CREATED ON SYSTEM_ERROR_LOGS (CREATED_AT DESC);
CREATE INDEX IDX_ERRLOG_STATUS ON SYSTEM_ERROR_LOGS (HTTP_STATUS);
